image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
    - build
    - test

variables:
    src_dir: "./HelloFunction/src/HelloFunction" 
    test_dir: "./HelloFunction/test/HelloFunction.Tests"
    
before_script:
    - echo "pre script"
    
build:
    stage: build
    script:
        - echo "building..."
        - "cd $src_dir"
        - "dotnet build"
        - "cd ../../../"

test:
    stage: test
    script: 
        - echo "testing..."
        - "cd $test_dir"
        - "dotnet test"